name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs

    - name: Mamba install JupyterLab 2
      shell: bash -l {0}
      run: mamba install jupyterlab=2 ipywidgets=7.6

    - name: Install here-map-widget-for-jupyter
      shell: bash -l {0}
      run: |
        npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/here-node/
        cd js
        npm install --legacy-peer-deps
        npm run build
        cd ..
        pip install .[dev]

    - name: Install JupyterLab extension
      shell: bash -l {0}
      run: |
        jupyter nbextension install --py --symlink --sys-prefix here_map_widget
        jupyter nbextension enable --py --sys-prefix here_map_widget
        jupyter labextension install js

    - name: Check installation files
      shell: bash -l {0}
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/map-widget-for-jupyter/index.js

    - name: Lint check
      shell: bash -l {0}
      run: make lint

    - name: Import check
      shell: bash -l {0}
      run: python -c 'import here_map_widget'

    - name: Build docs (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |
        mamba install sphinx sphinx_rtd_theme
        pip install -r docs/requirements.txt
        cd docs
        make html
